# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91c1e3fc4a2a0cebe4e8fbae8094365f210aa7d4f57012e64cb111baed39b7fe19b7a47dffb18c03bdf07660d01e7ea7f3d70c33660cd8edee0c0480c908dec9

test:
  secret_key_base: c4a16dc4cec247655a61bfc57ebf49f13f0fd875e81273faf083fa24a9884ff7ba3219ce2f01e804b74a8187a53a16c6d84f91b76ef47aa2a3b4c41fafe35d0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
